name: ci

on:
  push:
    branches: [develop, main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: OmniSurg/omnisurg-infrastructure/.github/workflows/reusable-go-library-ci.yml@main
    with:
      module_dir: "."
